dropbox/djinni

example/README.md, example/local.properties.sample
When trying to build the android example, some users might run into the problem
where the path to the Android NDK is not properly setup, so gradle fails to
build the project.
As proposed in #8, this PR adds a `local.properties.sample` file, as well as a
troubleshooting section in the README.md, which describes how to solve the
problem.
=> Add sample file and documentation for NDK path specification

support-lib/jni/HString.hpp
Passing the result of c_str() to a function that takes std::string as argument is slow and redundant.
=> Avoid unnecessary conversion and temporaries

src/source/JNIGenerator.scala
Otherwise, JNI support lib includes break if hpp-ext is set to anything other than hpp.
=> Don't apply cppHeaderExt to JNI base libs

src/source/ObjcGenerator.scala
This fixes the case where the Objective-C++ namespace is different from the C++ namespace.
In a code base I'm working on, for instance, the Objective-C++ namespace is set to "djinni_generated", whereas the C++ namespace is like "foo::bar". Djinni would produce broken Objective-C++ code before this patch in that configuration.
If these namespaces should always be identical, then either the C++ namespace should be forced single-level or the Objective-C++ namespace should be able to be multi-level. Currently, if one has picked a multi-level C++ namespace, one is forced to have a separate Objective-C++ namespace.
I'm guessing that the behavior prior to this patch is an accident, since the absolute C++ namespace is inserted on the type in the constructor.
=> Correct namespace for ObjcProxy return types

support-lib/jni/djinni_support.cpp, support-lib/jni/djinni_support.hpp
Changes necessary to make Djinni build successfully on Windows with Microsoft Visual Studio 2013 and newer.
=> Work-arounds to make Djinni build on Windows with MSVC >=2013

src/source/ObjcGenerator.scala
Afaict the --objc-include-cpp-prefix flag was ignored until this change, probably unintentionally.
=> Include cpp prefix in Objective-C C++ includes

Makefile
Gyp no longer supports Android, this commit freezes it at the last version that did.
=> Freeze gyp

example/android/app/build.gradle
Without this Djinni looks for a specific older version.  There are no specific reasons to prefer any version, so I'm pegging it to the latest, which new developers should be most likely to have.  I found custom scripts online for automatically searching for the latest version, but don't want to pull in that level of complexity to our examples at the moment.
=> Upgrade Android example to expect latest SDK

Makefile, example/run_djinni.sh, src/build, src/run, src/run-assume-built, src/support/sbt, test-suite/run_djinni.sh
Everything works in a dir with spaces in the path, except for the
Android NDK build of the example, which is a limitation of the NDK.
I also made some cleanups to the Makefile along the way: Reordered the
clean rule to clean up gyp artifacts after they’re regenerated (from
inside NDK), and to directly access the test suite.
Closes issue #23
=> Build script improvements for paths with spaces

support-lib/jni/Marshal.hpp
This optimization is usually disabled if not all paths return the same local object.
=> Enable NRVO in JNI's Binary::toCpp

src/source/ObjcGenerator.scala, test-suite/generated-src/objc/DBAssortedIntegers.mm, test-suite/generated-src/objc/DBClientReturnedRecord.mm, test-suite/generated-src/objc/DBConstants.mm, test-suite/generated-src/objc/DBDateRecord.mm, test-suite/generated-src/objc/DBMapDateRecord.mm, test-suite/generated-src/objc/DBMapListRecord.mm, test-suite/generated-src/objc/DBMapRecord.mm, test-suite/generated-src/objc/DBNestedCollection.mm, test-suite/generated-src/objc/DBPrimitiveList.mm, test-suite/generated-src/objc/DBRecordWithDerivings.mm, test-suite/generated-src/objc/DBRecordWithNestedDerivings.mm, test-suite/generated-src/objc/DBSetRecord.mm
Apple [docs](https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Protocols/NSObject_Protocol/index.html#//apple_ref/occ/intfm/NSObject/isEqual:) mention that one should always override `hash` when
implementing equality and overriding `isEqual:`.
This is not the smartest hashing but better than nothing.
=> objc: also implement `hash` when implementing `isEqual:`

src/source/ObjcppGenerator.scala, test-suite/generated-src/objc/DBClientInterface+Private.mm, test-suite/generated-src/objc/DBToken+Private.mm
This prevents Djinni-generated code from causing warnings when compiled with
`-Wstrict-selector-match`. See ["A big weakness in Objective-C's weak typing"](http://www.cocoawithlove.com/2011/06/big-weakness-of-objective-c-weak-typing.html) for details.
=> Cast handle

example/README.md
I was working through the example project today, and ran into some additional Android error messages.
I've added the errors I encountered and the solutions to the example's readme, so hopefully they will help others getting started with Djinni.
A couple of the issues may be due to different versions of Gradle, and changing a line or two in the .gradle file seems  to fix them. I was worried that this would break the example for users with different versions of Gradle, however, so didn't implement the fix in the source.
Great job and many thanks for such a useful tool!
=> Adding more Android error troubleshooting to example readme

Makefile
Unclear if this is the best way to do it, but I wanted a way to build djinni from the top-level directory without having to build any examples or tests.
=> Add a makefile rule to _only_ build djinni proper

src/source/ObjcGenerator.scala, test-suite/generated-src/objc/DBAssortedPrimitives.mm, test-suite/generated-src/objc/DBClientReturnedRecord.mm, test-suite/generated-src/objc/DBConstants.mm, test-suite/generated-src/objc/DBDateRecord.mm, test-suite/generated-src/objc/DBEmptyRecord.mm, test-suite/generated-src/objc/DBExternRecordWithDerivings.mm, test-suite/generated-src/objc/DBMapDateRecord.mm, test-suite/generated-src/objc/DBMapListRecord.mm, test-suite/generated-src/objc/DBMapRecord.mm, test-suite/generated-src/objc/DBNestedCollection.mm, test-suite/generated-src/objc/DBPrimitiveList.mm, test-suite/generated-src/objc/DBRecordWithDerivings.mm, test-suite/generated-src/objc/DBRecordWithDurationAndDerivings.mm, test-suite/generated-src/objc/DBRecordWithNestedDerivings.mm, test-suite/generated-src/objc/DBSetRecord.mm
This is a somewhat crude implementation of `debugDescription` in Objective-C.
We use the trick of boxing all the primitives so emitting the format string is easier.
`debugDescription` is used by lldb when using `po` and makes debugging really really nice.
=> Improve Objective-C debug descriptions for record types

src/source/CppGenerator.scala, test-suite/generated-src/cpp/assorted_primitives.hpp, test-suite/generated-src/cpp/client_returned_record.hpp, test-suite/generated-src/cpp/constants.hpp, test-suite/generated-src/cpp/date_record.hpp, test-suite/generated-src/cpp/extern_record_with_derivings.hpp, test-suite/generated-src/cpp/map_date_record.hpp, test-suite/generated-src/cpp/map_list_record.hpp, test-suite/generated-src/cpp/map_record.hpp, test-suite/generated-src/cpp/nested_collection.hpp, test-suite/generated-src/cpp/primitive_list.hpp, test-suite/generated-src/cpp/record_with_derivings.hpp, test-suite/generated-src/cpp/record_with_duration_and_derivings.hpp, test-suite/generated-src/cpp/record_with_nested_derivings.hpp, test-suite/generated-src/cpp/set_record.hpp
adds a _ before variable names to prevent a warning.
Clang emits “Declaration shadows a field of …” when using the same variable name in the constructor. I googled a bit but couldn’t find a best practice besides `new_` which seems excessive long, so I settled with just an underscore.
Before:
After:
=> No shadow constructor variables

src/source/ObjcppGenerator.scala
In certain situations with nonnull support the objcpp file did not include the nonnull header. This fixes the problem.
=> Fix missing nonnull include file for objcpp files.

support-lib/jni/Marshal.hpp, support-lib/jni/djinni_support.cpp
This addresses most but not all of the warnings in #152.  See my notes in the issue for my best theory on the remaining ones.
This appears stable in Dropbox code, but LocalRef leaks can be hard to detect.  @j4cbo @mknejp I could use another set of eyes on this before I merge it.
=> Add extra exception checks based on warnings

test-suite/Makefile, test-suite/README.md, test-suite/java/build.xml, test-suite/java/docker/README.md
This change:
* Prints a nice error message if the user is missing cmake.  I tested it by running the build in docker with `cmake` removed
* Moves the docker tests out of the `all` target for the test suite.  I checked they still work by running `make linux_docker`.
* Patches docs in a couple of places to make the Docker dependency easier to find.
In response to discussion at: https://github.com/dropbox/djinni/pull/140#issuecomment-155940221
✓ I have previously signed the Dropbox CLA
=> Some patches for djinni veterans

support-lib/objc/DJIMarshal+Private.h
The specified `ObjcType` in all of these is the immutable counterpart (`NSArray,` `NSSet`, and `NSDictionary`) so returning a mutable instance was unnecessary. This has a few added benefits:
- **Guarantees immutability**: even though the types were immutable, one can (though obviously discouraged) mutate the instances.
- **Optimizes memory usage**: it's common in Objective-C to perform *defensive copying* (I've seen Djinni does this in a few places). By copying early we guarantee that only one copy is made, rather than each class creating its own copy (remember that calling `-copy` on an immutable instance simply returns `this`).
- **Optimizes performance**: immutable implementations of these classes in `Foundation` are potentially better optimized for searching and fetching, since they …
=> Returning immutable Objective-C collections when converting from C++

src/source/ObjcGenerator.scala, test-suite/generated-src/objc/DBMapDateRecord.mm, test-suite/generated-src/objc/DBMapListRecord.mm, test-suite/generated-src/objc/DBMapRecord.mm, test-suite/generated-src/objc/DBNestedCollection.mm, test-suite/generated-src/objc/DBPrimitiveList.mm, test-suite/generated-src/objc/DBSetRecord.mm
This is a small follow up to #123. The `ObjcGenerator` was already correctly set up to automatically copy `NSString` instances to ensure that if an `NSMutableString` instance was passed instead, an immutable copy was created.
With this change the same is true for `NSSet`, `NSArray`, and `NSDictionary` properties.
Note that thanks to #123 this should not have a performance impact (neither memory or CPU), since at most only one copy will be made.
=> Objective-C generated classes copy collection types in constructor

support-lib/java/com/dropbox/djinni/NativeLibLoader.java, test-suite/java/build.xml
Avoid using Java 8 features in NativeLibLoader, and add compile checks to keep us at 1.7 (at least for now).
@pwais, can you confirm that this works for you? I think it's identical -- we were passing 1 for `maxDepth` to `Files.walk`, so replacing it with list-one-directory calls should be equivalent, but please check.
More generally, there's a question of which version of Java we should be targeting. On the C++ and ObjC sides, Djinni is aggressive in using the very latest. On the Java side, given the state of Java 8 on Android, I think it's worth being more conservative for now. The changes needed to go back to 7 here aren't extensive or particularly painful. If they were, or if at any point in the future we stand to gain a lot from requiring Java 8, then we should definitely do so. (But …
=> Support lib: target Java 7, not 8

example/generated-src/cpp/sort_items.hpp, example/generated-src/cpp/textbox_listener.hpp, example/generated-src/objc/TXSItemList.mm, src/source/CppGenerator.scala, src/source/CppMarshal.scala, test-suite/generated-src/cpp/client_interface.hpp, test-suite/generated-src/cpp/extern_interface_2.hpp, test-suite/generated-src/cpp/test_helpers.hpp, test-suite/handwritten-src/cpp/test_helpers.cpp
Fixes #165.
Not tested except of on one sample project mentioned in #164.
---
Note that I never [seriously] learned Scala, also I'm not too familiar with Djinni itself, so don't expect the pull request be a quality one.
=> Forward declare instead of #include enums/records from interface's hpp

example/localhost/Dockerfile
utopic is no longer supported (although still appearing in the docker hub), when running `apt-get update` inside the docker I get many 404 messages such as:
```
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/main/source/Sources  404  Not Found [IP: 91.189.91.23 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/restricted/source/Sources  404  Not Found [IP: 91.189.91.23 80]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/utopic/universe/source/Sources  404  Not Found [IP: 91.189.91.23 80]
```
Changed `FROM` to `vivid`, everything works as expected now.
=> Change base ubuntu version in Dockerfile from utopic to vivid

support-lib/jni/Marshal.hpp
Sets of primitive Java types aren't properly boxed when moved to Java which causes crashes. This PR brings Set marshaling to be equivalent to List marshaling with proper boxing and `HashSet` initialization of proper size.
=> Fix crash when marshaling sets to Java

src/source/parser.scala
If djinni files were at the root level of the project and one file imported another it would fail with a "null/<filename>" not found.  This fix makes the fileParent a function that tests for nullness and just returns the empty string if necessary.
=> root import error

src/source/CppMarshal.scala
Previously, the nn header was only included when the argument or return
type of an interface's method was not equal to the interface itself.
Fixes #197
=> CppMarshal: Always emit nn header include for interface

src/source/generator.scala
When --skip-generation is enabled yaml files aren't be added to the out file list.
=> add yaml files to outFileList when --skip-generation is enabled

src/source/ObjcppGenerator.scala
Fixes #137
No functionality change if not using "--ident-cpp-type"
=> Fix ObjC interface generated with non-default cpp identifier type formatting

example/generated-src/jni/NativeSortItems.cpp, src/source/JNIGenerator.scala, test-suite/generated-src/jni/NativeConstantsInterface.cpp, test-suite/generated-src/jni/NativeCppException.cpp, test-suite/generated-src/jni/NativeExternInterface1.cpp, test-suite/generated-src/jni/NativeListenerCaller.cpp, test-suite/generated-src/jni/NativeReturnOne.cpp, test-suite/generated-src/jni/NativeReturnTwo.cpp, test-suite/generated-src/jni/NativeReverseClientInterface.cpp, test-suite/generated-src/jni/NativeTestDuration.cpp, test-suite/generated-src/jni/NativeTestHelpers.cpp, test-suite/generated-src/jni/NativeUserToken.cpp, test-suite/generated-src/jni/NativeUsesSingleLanguageListeners.cpp
The Compiler had some issues finding the CppProxy, cause we were using foobar::djinni as namespace for generated djinni files. I changed in the JNIGenerator.scala file the namespace for the CppProxy to the global Namespace. Then the compiler could find the CppProxy and everything was alright for us.
The Problem was during compiling for Android with NDK r11b and the shipped clang compiler 3.6.
=> Changed Namespace for CppProxy to global ::djinni in JNIGenerator

src/source/CppGenerator.scala, src/source/CppMarshal.scala
This is easily triggered by the following kinds of methods:
```
interface node {
}
interface tree +c {
node(): node;
is_any_of(nodes: set<node>): bool;
}
```
(Apologies for the nonsensical example.)
Both are fixed by using the type's fully qualified name
if the scope contains conflicting names/symbols.
=> Fix shadowing of C++ type names by similar method names.

support-lib/djinni_common.hpp, support-lib/jni/djinni_support.cpp, support-lib/jni/djinni_support.hpp
I added and used more macros in djinni_common for hiding VS2015 limitations, instead of having several #ifdef _MSC_VER everywhere
=> Cleaner fix for VS2015

support-lib/jni/djinni_support.cpp
=> Don't leak local refs when creating WeakReference objects.

support-lib/jni/djinni_support.cpp
The workaround for a bug #264 
This error is similar to a bug in the compiler. Any calls to methods of the class std::wstring in the method implWStringToUTF16<2> led to the link error. If you call methods from other places, the error did not occur. I made to implWStringToUTF16 took iterators, thus removing all calls to methods of the class std::wstring from it. This implementation works on mac and linux
=> Build java tests on mac workaround

src/source/Main.scala
Djinni crashes if the options "--in-file-list ' and '--out-file-list" contains only the file names. If the path contains the folder name, the program does not crash.
For example:
>> djinni --idl test.djinni --list-out-files somefile.txt
Already up to date: Djinni
Parsing...
Resolving...
Generating...
Exception in thread "main" java.lang.NullPointerException
at djinni.generatorTools.package$.createFolder(generator.scala:172)
at djinni.Main$.main(Main.scala:275)
at djinni.Main.main(Main.scala)
if the path to explicitly specify a folder, then everything is OK:
>> djinni --idl test.djinni --list-out-files ./somefile.txt
Already up to date: Djinni
Parsing...
Resolving...
Generating...
=> Fixed crash

intellij-plugin/META-INF/plugin.xml
The plugin does not work with 131 only as it is missing some API class(es).
Api Level 139 is supported by IDEA 14+, Android Studio 1.3+, AppCode 3.3+ and PyCharm 4+. (Only verified IDEA 14 & AppCode 3.3, the rest are taken from http://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html )
=> Set minimum compatible IDEA API version to 139.

intellij-plugin/META-INF/plugin.xml
Update intellij plugin description to include license text to be sure uploading the plugin to the jetbrains plugin repository is in compliance with the license.
Make the github project be the vendor. This way there can be no mistake where the plugin comes from. It also provides a way to get in contact.
=> IntelliJ plugin descriptor changes in preparation of uploading it to the public repository.

Makefile, test-suite/Makefile
From the Slack discussion channel: https://mobilecpp.slack.com/archives/general/p1478766914000338
In short, the Makefiles say that the iOS targets need to run on a simulator that's running ios 9.3, which causes the iOS targets to fail if you have the latest version of Xcode installed. This change updates the Makefiles to specify ios 10.1.
=> Update ios version in Make targets to 10.1.

README.md, example/example.yaml, intellij-plugin/src/com/dropbox/djinni/ideaplugin/YamlLexer.java, intellij-plugin/src/com/dropbox/djinni/ideaplugin/_DjinniLexer.java, support-lib/proxy_cache_interface.hpp, test-suite/handwritten-src/cpp/optional.hpp
Hi,
this merge request fixes some minor issues.
It was created with help of [Feram][repo].
If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊
PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].
[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co
=> Minor Fixes

support-lib/jni/djinni_support.cpp
djinni_support.cpp:485: error: unused parameter
=> fixing error from clang (issue #294)

CONTRIBUTORS, README.md, support-lib/jni/djinni_support.hpp, support-lib/proxy_cache_interface.hpp
Please consider the following changes - these fix build issues in our environment, and perhaps will help others.
- Adding :: to djinni namespace inside the DJINNI_ASSERT macros. This is already done in other macros in the file, and prevents a deeper namespace from being chosen inadvertently.
- proxy_cache_interface.hpp uses shared_ptr in a template class without including <memory>.
- Something about objectFromHandleAddress() is causing the compiler to segfault on the specified line. Not sure why (still investigating), but in the meantime, the temporary variable allows the compiler to complete.
Thanks!
=> Cppfixes 201704

support-lib/jni/djinni_support.cpp, support-lib/jni/djinni_support.hpp
Fix Djinni initialization crash in multi shared library case (i.e. djinni_support_lib is a shared library used by other shared libraries).
Crash is observed in Android Studio 2.3 with NDK+cmake setup when hitting assert statement: 
```
class JniClass {
public:
static const C & get() {
(void)s_initializer;
assert(s_singleton); // Crashes here
return *s_singleton;
}
```
My understanding of the problem is that static_registration class template header is included in two different translation units in the shared libs and so results in bad initialization of the JniClassInitializer map.
Explicit template specialization of static_registration<void *, const JniClassInitializer>::get_map() in the cpp file is a way to force that get_map method to a single translation unit and so enforce its …
=> [Android] Fix Djinni initialization crash in multi shared library case

support-lib/jni/djinni_support.cpp
This avoids the warning
```
/project/support-lib/jni/djinni_support.cpp:61:37: warning: unused exception parameter 'e' [-Wunused-exception-parameter]
} catch (const std::exception & e) {
^
1 warning generated.
```
=> Avoid unused variable warning when compiling djinni_support.cpp

src/source/CppGenerator.scala, src/source/JavaGenerator.scala, src/source/Main.scala, src/source/YamlGenerator.scala, src/source/ast.scala, src/source/generator.scala, src/source/meta.scala, src/source/parser.scala, test-suite/djinni/enum.djinni, test-suite/djinni/nested_collection.djinni, test-suite/djinni/primtypes.djinni, test-suite/djinni/vendor/third-party/date.djinni, test-suite/djinni/vendor/third-party/date.yaml, test-suite/generated-src/java/com/dropbox/djinni/test/AssortedPrimitives.java, test-suite/generated-src/java/com/dropbox/djinni/test/DateRecord.java, test-suite/generated-src/java/com/dropbox/djinni/test/EnumUsageRecord.java, test-suite/generated-src/java/com/dropbox/djinni/test/NestedCollection.java, test-suite/handwritten-src/java/android/os/Parcel.java, test-suite/handwritten-src/java/android/os/Parcelable.java, test-suite/handwritten-src/java/com/dropbox/djinni/test/AllTests.java, test-suite/handwritten-src/java/com/dropbox/djinni/test/AndroidParcelableTest.java, test-suite/run_djinni.sh
Implemented support for android.os.parcelable
it's possible to apply this to the entire project via command-line `--java-implement-android-os-parcelable true` or per record `deriving(parcelable)`.
This PR is a continuation of https://github.com/dropbox/djinni/pull/257.
I picked the work done by @konovalov-aleks and apply the code review changes requested by @artwyman.
I don't claim the credits of this work to me, all the credit's should go to @konovalov-aleks.
=> Android parcelable support

src/build.sbt, src/project/build.properties
Per http://docs.scala-lang.org/overviews/jdk-compatibility/overview.html, Scala 2.11.12 and sbt 0.13.17 are the minimum versions supporting JDK 9.
Refs #356.
=> Upgrade sbt and scala version dependencies for JDK 9 compatibility

src/source/JavaGenerator.scala, test-suite/generated-src/java/com/dropbox/djinni/test/Conflict.java, test-suite/generated-src/java/com/dropbox/djinni/test/ConflictUser.java, test-suite/generated-src/java/com/dropbox/djinni/test/ConstantsInterface.java, test-suite/generated-src/java/com/dropbox/djinni/test/CppException.java, test-suite/generated-src/java/com/dropbox/djinni/test/EnumUsageInterface.java, test-suite/generated-src/java/com/dropbox/djinni/test/ExternInterface1.java, test-suite/generated-src/java/com/dropbox/djinni/test/FlagRoundtrip.java, test-suite/generated-src/java/com/dropbox/djinni/test/InterfaceUsingExtendedRecord.java, test-suite/generated-src/java/com/dropbox/djinni/test/ListenerCaller.java, test-suite/generated-src/java/com/dropbox/djinni/test/ReturnOne.java, test-suite/generated-src/java/com/dropbox/djinni/test/ReturnTwo.java, test-suite/generated-src/java/com/dropbox/djinni/test/ReverseClientInterface.java, test-suite/generated-src/java/com/dropbox/djinni/test/TestDuration.java, test-suite/generated-src/java/com/dropbox/djinni/test/TestHelpers.java, test-suite/generated-src/java/com/dropbox/djinni/test/UserToken.java, test-suite/generated-src/java/com/dropbox/djinni/test/UsesSingleLanguageListeners.java, test-suite/generated-src/java/com/dropbox/djinni/test/VarnameInterface.java, test-suite/generated-src/java/com/dropbox/djinni/test/WcharTestHelpers.java
This prevents compilation errors when someone creates a djinni interface with their own method named "destroy()".
=> Rename destroy() to __destroy()

src/source/Main.scala, src/source/generator.scala
This adds some simple logic to check whether files are set to overwrite each other. This is especially helpful for newcomers who are confused when the default settings cause this issue. Fixes #380
=> Check for Duplicate Output Paths

src/source/CppGenerator.scala, test-suite/generated-src/cpp/constants.cpp, test-suite/generated-src/cpp/constants_interface.cpp
Fix compile error: ‘constexpr’ needed for in-class initialization of static data member.
=> Use ‘constexpr’ in generated `.cpp` files

README.md
This PR adds Android Parcelable records documentation that was missing in https://github.com/dropbox/djinni/pull/308
=> Add Android Parcelable records documentation

src/build.sbt
The following build warning is emitted when running src/build:
src/build.sbt:20: warning: method seq in trait BuildExtra is deprecated: In build.sbt files, this call can be removed.  In other cases, this can usually be replaced by Seq.
seq(SbtStartScript.startScriptForClassesSettings: _*)
The call cannot be removed without breaking the build script, but changing "seq" to "Seq" seems to do the trick.
Running make does not change to any of the existing test or example files.  All test cases pass.
=> Fix deprecation warning when running the build script

README.md
README instructions do not generate the files they say they will generate, fix the djinni command called so that they match up.
Replaces #400 - apologies for duplicate pull request, I accidentally did the initial request from master instead of a branch and needed to free my master up for other changes.
=> Fix misleading README instructions

src/run
When running with git bash, the platform is `MSYS_NT` so a conditional had to be added to allow generation to run the correct batch file when using this platform.
=> Add support for running Djinni with Git Bash on Windows 

support-lib/jni/djinni_support.cpp
Hello, first of all I would like to thank the folks who have contributed to this code base, I have never explored a more beautifully written C++ code base!!
Here is a small change that kind of was triggering my coding OCD :,). I don't think ```size``` gets modified anywhere so I made it const (please correct me if I am wrong).
Moreover, if time permits I would really appreciate if a few of my curiosities can be answered (for learning purposes):
on line ```466``` and ```467``` of ```djinni_support.cpp``` we have the following:
```cpp
(void)implWStringToUTF16<2>;
(void)implWStringToUTF16<4>;
```
Could we not change the ```(void)``` to one of the following solutions ? or is there something wrong with them? and why is ```(void)``` more useful over them.
- SOLUTION 1: Template Function
```cpp …
```
=> Make "const auto" where variable not being modified and ask about (void).

src/source/CppGenerator.scala, test-suite/generated-src/cpp/access_flags.hpp, test-suite/generated-src/cpp/empty_flags.hpp
In GCC 7.2, the bitwise assignment operators generated for C++ flags can not be constexpr, causing the build to fail. This patch makes them inline instead. Also, the second argument is made const to silence some diagnostics in Visual Studio.
=> Fixes error: expression is not a constant expression

common.gypi, example/android/app/build.gradle, example/android/app/jni/Application.mk, example/android/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties
The Android example project it's not building anymore due to multiple incompatibilidades with the last Android Studio release 3.3.2 as today.
So I fix all the issues, because this was not letting me run the command `make all` with success.
Where it was possible I created a comment near the issue, showing the error, for future documentation on why things changed.
=> Fix build Android example project

example/example.djinni, example/run_djinni.sh, src/source/JavaGenerator.scala, test-suite/djinni/client_interface.djinni, test-suite/djinni/constant_enum.djinni, test-suite/djinni/derivings.djinni, test-suite/djinni/enum_flags.djinni, test-suite/djinni/map.djinni, test-suite/djinni/primitive_list.djinni, test-suite/djinni/vendor/third-party/duration.yaml, test-suite/djinni/yaml-test.djinni, test-suite/generated-src/java/com/dropbox/djinni/test/ClientReturnedRecord.java, test-suite/generated-src/java/com/dropbox/djinni/test/ConstantWithEnum.java, test-suite/generated-src/java/com/dropbox/djinni/test/MapListRecord.java, test-suite/generated-src/java/com/dropbox/djinni/test/MapRecord.java, test-suite/generated-src/java/com/dropbox/djinni/test/PrimitiveList.java, test-suite/generated-src/java/com/dropbox/djinni/test/RecordWithDerivings.java, test-suite/generated-src/java/com/dropbox/djinni/test/RecordWithFlags.java, test-suite/generated-src/java/com/dropbox/djinni/test/RecordWithNestedDerivings.java, test-suite/run_djinni.sh
The Flag type was added, but the support for parcelable for it was missing, so this PR add's it.
This also fixes https://github.com/dropbox/djinni/issues/431 and improves the test coverage for parcelable.
=> Fix some issues with parcelable code gen with enums and flags
